services:
  # 1. The Database
  db:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=3221
      - POSTGRES_DB=smart_farm
    ports:
      - "5433:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql

  # 2. The API
  api:
    build: .
    environment:
      - DB_HOST=db
      - DB_PASSWORD=3221
    ports:
      - "8000:8000"
    depends_on:
      - db

  # 3. The Simulator/Ingestion Engine
  engine:
    build: .
    environment:
      - DB_HOST=db
      - DB_PASSWORD=3221
    depends_on:
      seeder: # Wait for seeding to finish before simulating data
        condition: service_completed_successfully
  
  # seeder
  seeder:
    build: .
    command: python src/seed_db.py
    environment:
      - DB_HOST=db
      - DB_PASSWORD=3221
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data: